version: "3"
services:
  node-app:
    container_name: express-node-app-container
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
