version: "3"
services:
  node-app:
    container_name: express-node-app-container
    build: .
    volumes:
      - ./src:/app/src:ro # here we use relative path not absolute path  # with mode read only
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
